### ISSUE TITLE
Error sort-and-filter.php

### ISSUE THREAD

**Issue by APraxx** [johnwarne/reddit-top-rss#17]
Hi,
i have an issue and hope you still maintain this ;)
i don't know if there were some changes on reddit side or if my server had a hiccup

Here are the logs from docker:
```
2023-05-04 19:57:24,863 INFO supervisord started with pid 1
 2023-05-04 19:57:25,869 INFO spawned: 'nginx' with pid 7
 2023-05-04 19:57:25,876 INFO spawned: 'php-fpm' with pid 8
 [04-May-2023 19:57:25] NOTICE: fpm is running, pid 8
 [04-May-2023 19:57:25] NOTICE: ready to handle connections
 2023-05-04 19:57:26,957 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
 2023-05-04 19:57:26,958 INFO success: php-fpm entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
 192.168.16.28 - - [04/May/2023:19:58:00 +0000] "GET / HTTP/1.1" 200 1177 "-" "Mozilla/5.0 (Windows NT 10.0; rv:112.0) Gecko/20100101 Firefox/112.0" "172.20.0.1" 0.009 0.008 . -
 192.168.16.28 - - [04/May/2023:19:58:01 +0000] "GET /postlist.php?subreddit=worldnews&score=&threshold=&averagePostsPerDay= HTTP/1.1" 200 105 "https://reddit-top-rss.mysite.org/?subreddit=worldnews" "Mozilla/5.0 (Windows NT 10.0; rv:112.0) Gecko/20100101 Firefox/112.0" "172.20.0.1" 0.126 0.124 . -
 192.168.16.28 - - [04/May/2023:19:58:10 +0000] "GET /postlist.php?subreddit=worldnews&score=1&threshold=&averagePostsPerDay= HTTP/1.1" 200 105 "https://reddit-top-rss.mysite.org/?subreddit=worldnews&score=1" "Mozilla/5.0 (Windows NT 10.0; rv:112.0) Gecko/20100101 Firefox/112.0" "172.20.0.1" 0.074 0.072 . -
 NOTICE: PHP message: PHP Warning:  Trying to access array offset on value of type null in /var/www/html/sort-and-filter.php on line 25
 NOTICE: PHP message: PHP Warning:  Trying to access array offset on value of type null in /var/www/html/sort-and-filter.php on line 25
 NOTICE: PHP message: PHP Warning:  Trying to access array offset on value of type null in /var/www/html/sort-and-filter.php on line 25
 NOTICE: PHP message: PHP Warning:  Trying to access array offset on value of type null in /var/www/html/sort-and-filter.php on line 25
 NOTICE: PHP message: PHP Fatal error:  Uncaught TypeError: count(): Argument #1 ($var) must be of type Countable|array, null given in /var/www/html/sort-and-filter.php:25
 Stack trace:
 #0 /var/www/html/rss.php(17): include()
 #1 /var/www/html/index.php(25): include('...')
 #2 {main}
   thrown in /var/www/html/sort-and-filter.php on line 25
 192.168.16.22 - - [04/May/2023:19:58:25 +0000] "GET /?subreddit=technology&averagePostsPerDay=2&view=rss HTTP/1.1" 500 5 "-" "Mozilla/5.0 (compatible; Miniflux/2.0.43; +https://miniflux.app)" "-" 0.096 0.096 . -
 2023/05/04 19:58:25 [error] 9#9: *11 FastCGI sent in stderr: "PHP message: PHP Warning:  Trying to access array offset on value of type null in /var/www/html/sort-and-filter.php on line 25PHP message: PHP Warning:  Trying to access array offset on value of type null in /var/www/html/sort-and-filter.php on line 25PHP message: PHP Warning:  Trying to access array offset on value of type null in /var/www/html/sort-and-filter.php on line 25PHP message: PHP Warning:  Trying to access array offset
on value of type null in /var/www/html/sort-and-filter.php on line 25PHP message: PHP Fatal error:  Uncaught TypeError: count(): Argument #1 ($var) must be of type Countable|array, null given in /var/www/html/sort-and-filter.php:25
 Stack trace:
 #0 /var/www/html/rss.php(17): include()
 #1 /var/www/html/index.php(25): include('...')
 #2 {main}
   thrown in /var/www/html/sort-and-filter.php on line 25" while reading response header from upstream, client: 192.168.16.22, server: _, request: "GET /?subreddit=technology&averagePostsPerDay=2&view=rss HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "reddit-top-rss:8080"
```

i tried to make some sense of it and look if i could fix it myself but i dont know if it's a backend change of the json or something else?

hope you see this and thanks for providing this tool as long as you did

**Comment by LeftyLuke-87** [comment]
I have the same issue, this script stopped working

**Comment by ghost** [comment]
All of my reddit-top-rss feeds stopped working in early May.

Note that [the official API and RSS feeds will become paid starting from June 19](https://www.reddit.com/r/reddit/comments/12qwagm/an_update_regarding_reddits_api/) ([teddit.net](https://teddit.net/r/reddit/comments/12qwagm/an_update_regarding_reddits_api/)).

**Comment by pniewiadowski** [comment]
> All of my reddit-top-rss feeds stopped working in early May.

Same for me. Do you know any alternative as this seems to be not maintained anymore?

**Comment by miangraham** [comment]
This is a change on reddit's end. They're returning 429 and 403 in response to previously working queries for .json and .rss URLs.

After poking at it a bit, my working theory is that as part of slowly rolling out their [Data API changes announced last month](https://www.redditinc.com/blog/2023apiupdates), they've quietly begun to enforce the [User-Agent requirement documented here](https://github.com/reddit-archive/reddit/wiki/api#rules) for the data endpoints that this package uses, where previously it was (I believe) only needed for authenticated API requests.

Throwing the following plausible-looking string into functions.php got my curl requests to go through.

```php
curl_setopt($ch, CURLOPT_USERAGENT, "php:top.reddit.rss:v1.1.1");
```

This isn't enough by itself--similar settings are needed for the php built-in fetch functions whenever they're being used. But assuming I'm right on the above, this should be fixable in 5-10 lines.

This code has been my primary interface to reddit for the past year or two, so it would be nice to have it working again. If there are no other signs of activity, I'll see if I can put together a proper patch sometime this week.

**Comment by miangraham** [comment]
Fixes committed, PR opened. If we don't get a merge, anyone running from source can use my fork: https://github.com/miangraham/reddit-top-rss

I'll see about also building a new docker image in the next few days.

**Comment by miangraham** [comment]
Well, docker was easy. I threw together a GH Actions/Packages setup and built this patched image as a holdover. If you've been using the prebuilt container, you should be able to just grab this and run.

(see latest comment below for links)

**Comment by valkenrath** [comment]
Using your image. On [this line](https://github.com/miangraham/reddit-top-rss/blob/5f7347d1b6beaa9ae2ba5d3bd86636b82165fb6b/postlist.php#L18), should `$options` be `$reqOptions`?
When I make that change imperatively inside the container, everything works. Without it:
```
NOTICE: PHP message: PHP Warning:  Undefined variable $options in /var/www/html/postlist.php on line 18
```

**Comment by miangraham** [comment]
Yep, good catch, thanks. I stepped on that when squashing changes. PR updated, docker rebuilt and new container below.

Registry URL: ghcr.io/miangraham/reddit-top-rss@sha256:b231f880d9d3771a34d4b12be8cfb61d976144e8bb49524631099223a0b8f709

Usage:
```console
docker pull ghcr.io/miangraham/reddit-top-rss@sha256:b231f880d9d3771a34d4b12be8cfb61d976144e8bb49524631099223a0b8f709
```

[GH Package](https://github.com/miangraham/reddit-top-rss/pkgs/container/reddit-top-rss/92268878)

[GH Actions build](https://github.com/miangraham/reddit-top-rss/actions/runs/4941697000)

[Source](https://github.com/miangraham/reddit-top-rss/tree/dockerbuild) ([f15244f](https://github.com/miangraham/reddit-top-rss/commit/f15244f5514fc2db1dddb4b0703e1abcf5387ccd))

**Comment by APraxx** [comment]
@miangraham 
Thanks for the work.  
As i doubt this will be the last API related issue in the near future do you intent to keep your fork reasonable current if @johnwarne isn't available?


I'll leave this issue open for now

**Comment by miangraham** [comment]
If there are future easy fixes I'll chip in as needed when time permits.

Definitely agree with keeping this open until #18 is merged.

**Comment by johnwarne** [comment]
Hey all, apologies for the radio silence on this.

If I understand the communicated Reddit API changes correctly, we're very soon going to be required to connect to the Reddit API through OAuth, and publicly scraping the .json endpoints – even with an explicit user-agent string – will not be allowed.

Since this repo is also still my primary way of interacting with Reddit, I've been motivated to get my broken instance working again. For the past week I've been testing a fix for the issues that involves creating an app in your Reddit user account, and they seem to be working well. I've now updated the code, the Docker container, and the readme to reflect these changes. Anyone care to go through the outlined steps and let me know if anything is still not working?

**Comment by APraxx** [comment]
I'm glad your still working on this project and this is all that counts in my book.
I'll try it out and open a new issue.

thx everyone

**Comment by ghost** [comment]
a screenshot from the Reddit preferences page:

![image](https://github.com/johnwarne/reddit-top-rss/assets/14923168/f0aec838-57cb-493f-bd1e-1cd52c3bf2cf)

The string next the question mark icon, under `web app` is your `REDDIT_CLIENT_ID`

`redirect uri` can apparently be anything.
