### ISSUE TITLE
any docker support?

### ISSUE THREAD

**Issue by somedevreally** [johnwarne/reddit-top-rss#2]

**Comment by johnwarne** [comment]
I know this is super belated, but I've put an image on the Docker hub with instructions on running it. Hope this helps!

[https://hub.docker.com/repository/docker/johnny5w/reddit-top-rss](https://hub.docker.com/repository/docker/johnny5w/reddit-top-rss)

**Comment by somedevreally** [comment]
thanks and it works.
i already have wangqiru/mercury-parser-api and i use it as service with tt-rss like "service.mercury:3000" 
so in docker compose should MERCURY_URL=service.mercury or just mercury (as its internal host name?)
where can i find mercury parser's API?
in config.php i have set true for all the cache but i still see this error

```
NOTICE: PHP message: PHP Notice:  Undefined index: MERCURY_API_KEY in /var/www/html/config-default.php on line 18
NOTICE: PHP message: PHP Notice:  Undefined index: CACHE_REDDIT_JSON in /var/www/html/config-default.php on line 25
NOTICE: PHP message: PHP Notice:  Undefined index: CACHE_MERCURY_CONTENT in /var/www/html/config-default.php on line 32
NOTICE: PHP message: PHP Notice:  Undefined index: CACHE_RSS_FEEDS in /var/www/html/config-default.php on line 39
NOTICE: PHP message: PHP Notice:  Undefined index: CONFIG_VERSION in /var/www/html/config-default.php on line 46
```
thanks

**Comment by johnwarne** [comment]
Great to hear!

You’ll need to make sure that your services are on the same network to be able to talk to each other (internal, host, etc.). So your `service.mercury:3000` should work if they’re networked.

As for the error, I’m not at my computer, but in the Docker setup there’s no need for a `config.php` as the env variables take care of those settings. What does your docker-compose look like for just the reddit-top-rss service?

**Comment by somedevreally** [comment]
ok got it, i removed the config.php and added all the cache Parameters in docker-compose.

```
version: '3'
services:
  reddit:
    image: johnny5w/reddit-top-rss
    container_name: reddit
    restart: unless-stopped
    ports:
      - 80:8080
    environment:
      - DEFAULT_SUBREDDIT=news
      - MERCURY_URL=service.mercury:3000
      - CACHE_REDDIT_JSON=true
      - CACHE_MERCURY_CONTENT=true
      - CACHE_RSS_FEEDS=true
```
now i see this error, and ofcourse mercury API, how do i generate one?

```
NOTICE: PHP message: PHP Notice:  Undefined index: MERCURY_API_KEY in /var/www/html/config-default.php on line 18,
NOTICE: PHP message: PHP Notice:  Undefined index: CONFIG_VERSION in /var/www/html/config-default.php on line 46,
2020/05/10 22:10:18 [error] 10#10: *1 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined index: MERCURY_API_KEY in /var/www/html/config-default.php on line 18PHP message: PHP Notice:  Undefined index: CONFIG_VERSION in /var/www/html/config-default.php on line 46" while reading response header from upstream, client: x.x.x.x, server: _, request: "GET /postlist.php?subreddit=news&score=&threshold=&averagePostsPerDay= HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "x.x.x.x:port"

```
edit: yes the mercury parser is on same network

**Comment by johnwarne** [comment]
Hey there, looks like you’ll need to add your Mercury API key as an env variable as well. Could you try that next?

**Comment by somedevreally** [comment]
looks like api key is not needed.
and also mercury parser log shows proper parser for the url

**Comment by johnwarne** [comment]
Thanks for the heads up! I was working from an earlier understanding of the Mercury Parser service (before it was open-sourced). An API key should no longer be required. Can you test again after a pull and let me know if it's working as intended?

**Comment by somedevreally** [comment]
it's working, I don't see any api error on console.

Thanks

**Comment by johnwarne** [comment]
Thanks for testing and alerting me to this!
