### ISSUE TITLE
stop redirecting the frontpage to /r/pics

### ISSUE THREAD

**Issue by ghost** [johnwarne/reddit-top-rss#21]
Requests to `http://localhost/8080` are redirected to `http://localhost/8080?subreddit=pics`. Can you consider loading a blank page instead?

Currently I load the desired subreddit directly (see the second URL). A non-existing subreddit can also be used (e.g. `http://localhost/3000?subreddit=name`), but reddit-top-rss may keep making connection attempts.

**Comment by johnwarne** [comment]
You can load a different default subreddit by setting it in a `config.php` file (line 7) or a Docker environment variable (`DEFAULT_SUBREDDIT`).

**Comment by ghost** [comment]
> You can load a different default subreddit by setting it in a `config.php` file (line 7) or a Docker environment variable (`DEFAULT_SUBREDDIT`).

Fair enough. I'd still prefer defaulting to a page which doesn't load content from any subreddit.
